### ISSUE TITLE
dietpi proxmox

### ISSUE THREAD

**Issue by elRadix** [JOduMonT/DEB#1]
Hi,

Can you pls help me how to create  a dietpi proxox virtual server, it would be great if you can outline the steps end to end.

Thank you.

**Comment by JOduMonT** [comment]
@elRadix 
How did you try?
1. as a VM in KVM ?
2. with the Native PC (BIOS/CSM) or the Native PC (UEFI)
3. what is your error ?
4. do you have screenshot ?

**Comment by elRadix** [comment]
see screenshot and converted de the image to qcow2 format
![IMG_20200120_172120_388](https://user-images.githubusercontent.com/6258894/72742328-c3e07380-3ba9-11ea-8fbd-6d83156ec4d7.jpg)
![IMG_20200120_172049_658](https://user-images.githubusercontent.com/6258894/72742341-ccd14500-3ba9-11ea-8f79-b36e78748ce9.jpg)
![IMG_20200120_172040_184](https://user-images.githubusercontent.com/6258894/72742342-ccd14500-3ba9-11ea-875a-670475c38ca7.jpg)

**Comment by JOduMonT** [comment]
you should install from the ISO Native PC (BIOS/CSM) or the Native PC (UEFI) like any Linux

**Comment by elRadix** [comment]
that's what I now did using the ISO Native PC (UEFI) 

![image](https://user-images.githubusercontent.com/6258894/72843290-81e32a80-3c9a-11ea-8fec-f3135c96ac7c.png)

![image](https://user-images.githubusercontent.com/6258894/72843326-945d6400-3c9a-11ea-8eb1-9a12261f0d97.png)

**Comment by JOduMonT** [comment]
Now I could help you :)

1st the advantage of using an UEFI is you will be able to PCI Passthrough device such as a second GPU (Video) and use your VM to play kodi directly on your monitor/tv.

to do so you have to
1. change your **BIOS** type to **OVMF (UEFI)**
2. change you **Machine** type to **q35**
3. add a **EFI Disk** for ths UEFI Bios

![image](https://user-images.githubusercontent.com/5204724/72859751-770ab300-3cf7-11ea-9d38-3fe493863d6a.png)

With those change you will be able to install DietPi as usual.

**Comment by elRadix** [comment]
how do you create an efi disk with the size of 1M?
default is 128K

**Comment by elRadix** [comment]
I still get some errors
![image](https://user-images.githubusercontent.com/6258894/72920447-96323080-3d49-11ea-9ec0-de4904de15cf.png)
![image](https://user-images.githubusercontent.com/6258894/72920461-9f230200-3d49-11ea-829b-802c4ed371a4.png)

**Comment by JOduMonT** [comment]
it is before or after the installation of Diet Pi ?

**Comment by JOduMonT** [comment]
> how do you create an efi disk with the size of 1M?

@elRadix 
When you create the VM at the System step you have to use the **advance mode** than by choosing OVMF for the BIOS and specifying your storage it will create the EFI Disk automatically
![image](https://user-images.githubusercontent.com/5204724/73609240-577c6000-45fe-11ea-8581-61c08efe28d3.png)
